### ISSUE TITLE
Admin Login Form is not mobile-friendly

### ISSUE THREAD

**Issue by glenwinters** [thetwoj/wedding-frontend#4]
So squished. Right now it's getting `width: 20%` from [`.loginPaper`](https://github.com/thetwoj/wedding-frontend/blob/master/src/App.css#L258), so you just need to add a media query that makes it something like `width: 100%`.

![image](https://user-images.githubusercontent.com/435066/38159195-5c11e9be-3458-11e8-94bf-bfab90410903.png)

**Comment by thetwoj** [comment]
Fixed

![screen shot 2018-04-10 at 10 33 05 am](https://user-images.githubusercontent.com/1026447/38566974-9ecf8d92-3caa-11e8-9d57-ce0cecdccfd5.png)

**Comment by thetwoj** [comment]
Fixed, ty
